- name: App_setup
  ansible.builtin.import_role:
    name : common
    tasks_from: app_setup.yaml

- name: java_setup
  ansible.builtin.import_role:
    name : common
    tasks_from: java_setup.yaml

- name: Systemd_setup
  ansible.builtin.import_role:
    name : common
    tasks_from: systemd_setup.yaml

- name: install python dependencie
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL

- name: import shipping data
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: RoboShop@1
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name: Restart User service
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes