- name: Create EC2 instance and Route 53
  hosts: all
  connection: local
  vars: 
   sg_id: sg-0978bd3e9e6d67ee8
   ami_id: ami-0220d79f3f480ecf5
   domain_name: rakesh.bond
   env: dev
   instances:
   - mongodb
   - catalogue  
   - user
   - cart
   - shipping
   - payment
   - redis
   - mysql
   - rabbitmq
  tasks:
  - name: EC2 creation
    amazon.aws.ec2_instance:
      name: "{{ item }}-{{ env }}" #mongodb-dev
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}-{{ env }}"
        Project: Roboshop
        Environment: "{{ env }}"
        Component: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: Route 53 creation
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{item.item}}-{{ env}}.rakesh.bond" #mongodb-dev.rakesh.bond
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address}}"
    loop: "{{ ec2_output.results }}"
  
  - name: Route 53 creation
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{item.item}}-{{ env}}.rakesh.bond" #mongodb-dev.rakesh.bond
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address}}"
    loop: "{{ ec2_output.results }}"
    when: ec2_output.results == "frontend"
