[local]
localhost

[mongodb]
mongodb-DEV.rakesh.bond

[catalogue]
catalogue-DEV.rakesh.bond

[redis]
redis-DEV.rakesh.bond

[user]
user-DEV.rakesh.bond

[cart]
cart-DEV.rakesh.bond

[mysql]
mysql-DEV.rakesh.bond

[shipping]
shipping-DEV.rakesh.bond

[rabbitmq]
rabbitmq-DEV.rakesh.bond

[payment]
payment-DEV.rakesh.bond

[frontend]
frontend-DEV.rakesh.bond