- name: Enable nodejs:20
  ansible.builtin.command: dnf enable nodejs:20

- name: Install nodejs
  ansible.builtin.dnf:
   package: nodejs 
   state: present

- name: Install dependencies
  community.general.npm:
    path: /app
    state: present